Repository canonical-web-and-design/kubeflow-news.com, pull requests merged in 2019-07, with the labels that each got.

#6 Add newsletter sign up module
  templates/blog/_newsletter-signup.html
  templates/blog/_post.html
  templates/blog/archives.html
  templates/blog/article.html
  templates/blog/index.html
Labels: Review: Code +1, Review: QA +1

#8 Add homepage, post page and archives page
  .sass-lint.yml
  package.json
  requirements.txt
  static/sass/_pattern_buttons.scss
  static/sass/_pattern_card.scss
  static/sass/_pattern_footer.scss
  static/sass/_pattern_icons.scss
  static/sass/_pattern_lists.scss
  static/sass/_pattern_media.scss
  static/sass/_pattern_navigation.scss
  static/sass/_pattern_post.scss
  static/sass/_pattern_separator.scss
  static/sass/_pattern_strip.scss
  static/sass/_settings_colors.scss
  static/sass/styles.scss
  templates/_footer.html
  templates/_navigation.html
  templates/base.html
  templates/blog/_media-object.html
  templates/blog/_media-object_hero.html
  templates/blog/_newsletter-signup-form.html
  templates/blog/_newsletter-signup.html
  templates/blog/_pagination.html
  templates/blog/_post.html
  templates/blog/archives.html
  templates/blog/article.html
  templates/blog/index.html
  webapp/app.py
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#10 Add favicons
  requirements.txt
  templates/base.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#11 Updrade blog to 2.1.1
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#12 1422 feedback amends
  static/sass/_pattern_article.scss
  static/sass/_pattern_footer.scss
  static/sass/_pattern_icons.scss
  static/sass/_pattern_media.scss
  static/sass/_pattern_navigation.scss
  static/sass/_pattern_post.scss
  static/sass/_pattern_separator.scss
  static/sass/styles.scss
  templates/_footer.html
  templates/_navigation.html
  templates/base.html
  templates/blog/_media-object.html
  templates/blog/_media-object_hero.html
  templates/blog/_newsletter-signup-form.html
  templates/blog/_newsletter-signup.html
  templates/blog/_newsletter-success.html
  templates/blog/_post.html
  templates/blog/archives.html
  templates/blog/article.html
  templates/blog/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#16 Use TALISKER_REVISION_ID
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#17 Use kubeflow-news tag
  templates/blog/index.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#21 Update bug report link
  templates/_footer.html
Labels: Review: Code +1, Review: QA +1

#20 Centre images in blog posts
  static/sass/styles.scss
Labels: Review: Code +1, Review: QA +1

#22 Fix broken legal links on newsletter signup
  templates/blog/_newsletter-signup-form.html
Labels: Review: Code +1
