Repository canonical-web-and-design/kubeflow-news.com, pull requests merged in 2020-03, with the labels that each got.

#43 Multistage builds kubeflow-news.com
  .dockerignore
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#45 CI for docker images
  .github/workflows/tests.yml
Labels: Review: Code +1

#49 Move CI checks to github workflows
  .circleci/config.yml
  .github/workflows/pr.yml
  .github/workflows/tests.yml
Labels: Review: Code +1, Review: QA +1

#48 Replace sass-lint with stylelint
  .sass-lint.yml
  .stylelintrc
  package.json
  run
  static/sass/_pattern_buttons.scss
  static/sass/_pattern_card.scss
  static/sass/_pattern_lists.scss
  static/sass/_pattern_strip.scss
  static/sass/styles.scss
  yarn.lock
Labels: Review: Code needed, Review: QA needed

#50 Rename to pr.yaml
  .github/workflows/pr.yaml
Labels: Review: Code +1, Review: QA +1
